name = "maobidao"
main = "worker.js"
compatibility_date = "2026-05-27"
keep_vars = true

[vars]
GITHUB_OWNER = "iceeyes27"
GITHUB_REPO = "maobidao"
GITHUB_BRANCH = "main"

[secrets]
required = ["GITHUB_TOKEN", "SUBMIT_PASSWORD"]

[[kv_namespaces]]
binding = "STATS_KV"
id = "c25b289b65284d0c8e7ba329dc0a4c12"
preview_id = "c25b289b65284d0c8e7ba329dc0a4c12"

[assets]
directory = "./public"
binding = "ASSETS"
