name = "maobidao"
main = "worker.js"
compatibility_date = "2026-05-27"
keep_vars = true

[vars]
GITHUB_OWNER = "iceeyes27"
GITHUB_REPO = "maobidao"
GITHUB_BRANCH = "main"

[secrets]
required = ["GITHUB_TOKEN", "SUBMIT_PASSWORD"]

[[kv_namespaces]]
binding = "STATS_KV"
id = "YOUR_STATS_KV_NAMESPACE_ID"
preview_id = "YOUR_STATS_KV_PREVIEW_NAMESPACE_ID"

[assets]
directory = "./public"
binding = "ASSETS"
